name: transformers-project
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python>=3.9
  - pytorch>=2.0.0
  - numpy>=1.24.0
  - pandas>=2.0.0
  - jupyter
  - ipykernel
  - pip
  - pip:
    - tiktoken>=0.11.0
    - requests>=2.32.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - tqdm>=4.65.0